services:
  movieapi:
    build:
      context: .
      dockerfile: Services/Movie.API/DockerFile
    container_name: movieapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings__ConnectionString=mongodb://moviedb:27017
      - DatabaseSettings__DatabaseName=MovieDB
      - DatabaseSettings__CollectionName=Movies
    ports:
      - "8001:8080"
    depends_on:
      - moviedb
    restart: unless-stopped
    networks:
      - cinema-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  cinemaapi:
    build:
      context: .
      dockerfile: Services/Cinema.API/Dockerfile
    container_name: cinemaapi
    env_file:
      - .env
    environment:
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=cinemadb;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8000:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - cinema-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
