services:
  cinemadb:
    image: postgres:16
    container_name: cinemadb
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - cinema-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=cine.matf@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
    networks:
      - cinema-network

  cinemaapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cinemaapi
    env_file:
      - .env
    environment:
      - ConnectionStrings__Default=Host=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USERNAME};Password=${DB_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      - cinemadb
    restart: unless-stopped
    networks:
      - cinema-network

  moviedb:
    image: mongo:7
    container_name: moviedb
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    restart: unless-stopped
    networks:
      - cinema-network

  movieapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movieapi
    ports:
      - "8001:8080"
    depends_on:
      - moviedb
    restart: unless-stopped
    networks:
      - cinema-network

  screeningdb:
    image: postgres:16
    container_name: screeningdb
    environment:
      POSTGRES_DB: ScreeningDB
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - screeningpgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - cinema-network

networks:
  cinema-network:
    driver: bridge

volumes:
  pgdata:
  pgadmin_data:
  mongodata:
  screeningpgdata:
