server {
    listen 4200;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;


    location / {
        try_files $uri $uri/ /index.html;
    }
    # cache static files for one year
    location ~* \.(?:js|css|ttf|png|jpe?g|gif|svg|ico)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }
}
